version: "3.7"
services:
#  app:
#    build: .
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
#    links:
#      - db:rlvbvwgj
  db:
    image: "postgres:11.4"
    ports:
      - 5432:8080
    environment:
      PGHOST: localhost
      PGDATABASE: asttra_dev
      PGPASSWORD: astra_dev
      PGUSER: astra_dev

